const shoppingLists = {
  shopping_lists: [
    {
      id: '550e8400-e29b-41d4-a716-446655440000',
      name: 'My first list',
      products_quantity: 1,
      thumbnail_images: [
        'https://sta-mercadona.imgix.net/images/ed2f5303a6f0c6bac00c00f254f82fb5.jpg?fit=crop&h=300&w=300',
      ],
    },
    {
      id: 'e2a357db-d023-4967-85b0-2a84f3a15ee2',
      name: 'My second list',
      products_quantity: 2,
      thumbnail_images: [],
    },
  ],
}

const productShoppingLists = {
  shopping_lists: [
    {
      id: '918edf1c-f7a5-4460-8b28-b1a47b4c5638',
      name: 'Some user list',
      products_quantity: 4,
      in_list: false,
      thumbnail_images: [
        'https://sta-mercadona.imgix.net/images/ed2f5303a6f0c6bac00c00f254f82fb5.jpg?fit=crop&h=300&w=300',
        'https://sta-mercadona.imgix.net/images/6fe3bd1734dacc3f8751577ed526b7ab.jpg?fit=crop&h=300&w=300',
        'https://sta-mercadona.imgix.net/images/5fa8b3f8b45d41a01fc19622122fca72.jpg?fit=crop&h=300&w=300',
        'https://sta-mercadona.imgix.net/images/409a53c0327dff2c4b91e6b4c58efa42.jpg?fit=crop&h=300&w=300',
      ],
    },
    {
      id: '0191fa22-176e-7c35-811c-4eed128a7679',
      name: 'My second list',
      products_quantity: 2,
      in_list: true,
      thumbnail_images: [],
    },
  ],
}

const emptyShoppingListDetail = {
  id: '92fec5ce-9571-4fce-b3ef-67f387e8f642',
  name: 'my list',
  products_quantity: 0,
  items: [],
}

const shoppingListDetail = {
  id: '0191fa22-176e-7c35-811c-4eed128a7679',
  name: 'My second list',
  products_quantity: 2,
  items: [
    {
      product: {
        id: '52750',
        slug: 'bebida-kefir-fresa-platano-hacendado-botella',
        limit: 999,
        badges: {
          is_water: false,
          requires_age_check: false,
        },
        status: null,
        packaging: 'Bottle',
        published: true,
        share_url:
          'https://sta.tech.mercadona.es/product/52750/bebida-kefir-fresa-platano-hacendado-botella',
        thumbnail:
          'https://sta-mercadona.imgix.net/images/dd289147f3d6ee7437c4a9b701adf6ec.jpg?fit=crop&h=300&w=300',
        categories: [
          {
            id: 11,
            name: 'Dessert & yoghurt',
            level: 0,
            order: 597,
            categories: [
              {
                id: 108,
                name: 'Liquid yoghurt',
                level: 1,
                order: 597,
                categories: [
                  {
                    id: 866,
                    name: 'Cholesterol & others',
                    level: 2,
                    order: 597,
                  },
                ],
              },
            ],
          },
        ],
        display_name: 'strawberry and banana Kefir drink Hacendado',
        unavailable_from: null,
        price_instructions: {
          iva: 10,
          is_new: false,
          is_pack: false,
          pack_size: null,
          unit_name: null,
          unit_size: 0.25,
          bulk_price: '3.60',
          unit_price: '0.90',
          approx_size: false,
          size_format: 'kg',
          total_units: null,
          unit_selector: true,
          bunch_selector: false,
          drained_weight: null,
          selling_method: 0,
          price_decreased: false,
          reference_price: '3.600',
          min_bunch_amount: 1.0,
          reference_format: 'kg',
          previous_unit_price: null,
          increment_bunch_amount: 1.0,
        },
        unavailable_weekdays: [],
      },
      recommended_quantity: 1.0,
      source: 'shopping-list',
      source_code: 'SL',
    },
    {
      product: {
        id: '10672',
        slug: 'cafe-con-leche-descafeinado-hacendado-vaso',
        limit: 999,
        badges: {
          is_water: false,
          requires_age_check: false,
        },
        status: null,
        packaging: 'Glass',
        published: true,
        share_url:
          'https://sta.tech.mercadona.es/product/10672/cafe-con-leche-descafeinado-hacendado-vaso',
        thumbnail:
          'https://sta-mercadona.imgix.net/images/83a4f4b01c38d63142b2646afe4e1fa7.jpg?fit=crop&h=300&w=300',
        categories: [
          {
            id: 8,
            name: 'Chocolate drinks, coffee & tea',
            level: 0,
            order: 16,
            categories: [
              {
                id: 84,
                name: 'Soluble coffee & other drinks',
                level: 1,
                order: 16,
                categories: [
                  {
                    id: 372,
                    name: 'Cold drinks',
                    level: 2,
                    order: 16,
                  },
                ],
              },
            ],
          },
        ],
        display_name: 'Decaf caffe latte Hacendado',
        unavailable_from: null,
        price_instructions: {
          iva: null,
          is_new: false,
          is_pack: false,
          pack_size: null,
          unit_name: null,
          unit_size: 0.25,
          bulk_price: '3.00',
          unit_price: '0.75',
          approx_size: false,
          size_format: 'l',
          total_units: null,
          unit_selector: true,
          bunch_selector: false,
          drained_weight: null,
          selling_method: 0,
          price_decreased: false,
          reference_price: '3.000',
          min_bunch_amount: 1.0,
          reference_format: 'L',
          previous_unit_price: null,
          increment_bunch_amount: 1.0,
        },
        unavailable_weekdays: [],
      },
      recommended_quantity: 1.0,
      source: 'shopping-list',
      source_code: 'SL',
    },
    {
      product: {
        id: '24706',
        slug: 'alistado-mediano-congelado-granel',
        limit: 999,
        badges: {
          is_water: false,
          requires_age_check: false,
        },
        status: null,
        packaging: 'Bulk',
        published: true,
        share_url:
          'https://sta.tech.mercadona.es/product/24706/alistado-mediano-congelado-granel',
        thumbnail:
          'https://sta-mercadona.imgix.net/images/391487d7e55fc54688773f26f875a1ed.jpg?fit=crop&h=300&w=300',
        categories: [
          {
            id: 17,
            name: 'Frozen food',
            level: 0,
            order: 213,
            categories: [
              {
                id: 150,
                name: 'Seafood',
                level: 1,
                order: 213,
                categories: [
                  {
                    id: 516,
                    name: 'Seafood',
                    level: 2,
                    order: 213,
                  },
                ],
              },
            ],
          },
          {
            id: 2,
            name: 'Seafood & fish',
            level: 0,
            order: 441,
            categories: [
              {
                id: 32,
                name: 'Seafood',
                level: 1,
                order: 441,
                categories: [
                  {
                    id: 272,
                    name: 'Seafood',
                    level: 2,
                    order: 441,
                  },
                ],
              },
            ],
          },
        ],
        display_name: 'Frozen medium striped red shrimp',
        unavailable_from: null,
        price_instructions: {
          iva: 10,
          is_new: false,
          is_pack: false,
          pack_size: null,
          unit_name: null,
          unit_size: null,
          bulk_price: '36.75',
          unit_price: '3638.25',
          approx_size: true,
          size_format: 'kg',
          total_units: null,
          unit_selector: false,
          bunch_selector: true,
          drained_weight: null,
          selling_method: 1,
          price_decreased: false,
          reference_price: '36.750',
          min_bunch_amount: 0.15,
          reference_format: 'kg',
          previous_unit_price: null,
          increment_bunch_amount: 0.15,
        },
        unavailable_weekdays: [],
      },
      recommended_quantity: 0.15,
      source: 'shopping-list',
      source_code: 'SL',
    },
  ],
}

const shoppingListDetailMilkaElement = {
  product: {
    id: '12151',
    slug: 'chocolate-con-leche-milka-tableta',
    limit: 999,
    badges: {
      is_water: false,
      requires_age_check: false,
    },
    status: null,
    packaging: 'Pastilla',
    published: true,
    share_url:
      'https://sta.tech.mercadona.es/product/12151/chocolate-con-leche-milka-tableta',
    thumbnail:
      'https://sta-mercadona.imgix.net/images/e6cbab042ce93bc6756ef45ff91a19bc.jpg?fit=crop&h=300&w=300',
    categories: [
      {
        id: 9,
        name: 'Sucre, caramels i xocolate',
        level: 0,
        order: 11,
        categories: [
          {
            id: 92,
            name: 'Xocolate',
            level: 1,
            order: 11,
            categories: [
              {
                id: 381,
                name: 'Xocolate amb llet',
                level: 2,
                order: 11,
              },
            ],
          },
        ],
      },
    ],
    display_name: 'Chocolate con leche Milka',
    unavailable_from: null,
    price_instructions: {
      iva: 10,
      is_new: false,
      is_pack: false,
      pack_size: null,
      unit_name: null,
      unit_size: 0.15,
      bulk_price: '14.33',
      unit_price: '2.15',
      approx_size: false,
      size_format: 'kg',
      total_units: null,
      unit_selector: true,
      bunch_selector: false,
      drained_weight: null,
      selling_method: 0,
      price_decreased: false,
      reference_price: '14.334',
      min_bunch_amount: 1.0,
      reference_format: 'kg',
      previous_unit_price: null,
      increment_bunch_amount: 1.0,
    },
    unavailable_weekdays: [],
  },
  recommended_quantity: 1.0,
  source: 'shopping-list',
  source_code: 'SL',
}

const cartWithMilka = {
  id: '5529dc8b-0a94-4ae0-8145-de5186b542c6',
  version: 6,
  lines: [
    {
      quantity: 1.0,
      sources: ['+SL'],
      version: 4,
      product: {
        id: '12151',
        slug: 'chocolate-con-leche-milka-tableta',
        limit: 999,
        badges: {
          is_water: false,
          requires_age_check: false,
        },
        status: null,
        packaging: 'Tableta',
        published: true,
        share_url:
          'https://sta.tech.mercadona.es/product/12151/chocolate-con-leche-milka-tableta',
        thumbnail:
          'https://sta-mercadona.imgix.net/images/e6cbab042ce93bc6756ef45ff91a19bc.jpg?fit=crop&h=300&w=300',
        categories: [
          {
            id: 9,
            name: 'Azúcar, caramelos y chocolate',
            level: 0,
            order: 11,
          },
        ],
        display_name: 'Chocolate con leche Milka',
        unavailable_from: null,
        price_instructions: {
          iva: 10,
          is_new: false,
          is_pack: false,
          pack_size: null,
          unit_name: null,
          unit_size: 0.15,
          bulk_price: '11.33',
          unit_price: '1.70',
          approx_size: false,
          size_format: 'kg',
          total_units: null,
          unit_selector: true,
          bunch_selector: false,
          drained_weight: null,
          selling_method: 0,
          tax_percentage: '10.000',
          price_decreased: false,
          reference_price: '11.334',
          min_bunch_amount: 1.0,
          reference_format: 'kg',
          previous_unit_price: '2.15',
          increment_bunch_amount: 1.0,
        },
        unavailable_weekdays: [],
      },
    },
  ],
  open_order_id: null,
  summary: {
    total: '1.70',
  },
  products_count: 1,
}

const cartWithShoppingListDetail = {
  id: '321f46f4-7240-4bbe-a67d-fba10521ab46',
  version: 5,
  lines: [
    {
      quantity: 0.15,
      sources: ['+PL'],
      version: 5,
      product: {
        id: '24706',
        slug: 'alistado-mediano-congelado-granel',
        limit: 999,
        badges: {
          is_water: false,
          requires_age_check: false,
        },
        status: null,
        packaging: 'Bulk',
        published: true,
        share_url:
          'https://sta.tech.mercadona.es/product/24706/alistado-mediano-congelado-granel',
        thumbnail:
          'https://sta-mercadona.imgix.net/images/391487d7e55fc54688773f26f875a1ed.jpg?fit=crop&h=300&w=300',
        categories: [
          {
            id: 17,
            name: 'Frozen food',
            level: 0,
            order: 213,
          },
        ],
        display_name: 'Frozen medium striped red shrimp',
        unavailable_from: null,
        price_instructions: {
          iva: 10,
          is_new: false,
          is_pack: false,
          pack_size: null,
          unit_name: null,
          unit_size: null,
          bulk_price: '36.75',
          unit_price: '3638.25',
          approx_size: true,
          size_format: 'kg',
          total_units: null,
          unit_selector: false,
          bunch_selector: true,
          drained_weight: null,
          selling_method: 1,
          tax_percentage: '10.000',
          price_decreased: false,
          reference_price: '36.750',
          min_bunch_amount: 0.15,
          reference_format: 'kg',
          previous_unit_price: null,
          increment_bunch_amount: 0.15,
        },
        unavailable_weekdays: [],
      },
    },
    {
      quantity: 1.0,
      sources: ['+PL'],
      version: 4,
      product: {
        id: '10672',
        slug: 'cafe-con-leche-descafeinado-hacendado-vaso',
        limit: 999,
        badges: {
          is_water: false,
          requires_age_check: false,
        },
        status: null,
        packaging: 'Glass',
        published: true,
        share_url:
          'https://sta.tech.mercadona.es/product/10672/cafe-con-leche-descafeinado-hacendado-vaso',
        thumbnail:
          'https://sta-mercadona.imgix.net/images/83a4f4b01c38d63142b2646afe4e1fa7.jpg?fit=crop&h=300&w=300',
        categories: [
          {
            id: 8,
            name: 'Chocolate drinks, coffee & tea',
            level: 0,
            order: 16,
          },
        ],
        display_name: 'Decaf caffe latte Hacendado',
        unavailable_from: null,
        price_instructions: {
          iva: 10,
          is_new: false,
          is_pack: false,
          pack_size: null,
          unit_name: null,
          unit_size: 0.25,
          bulk_price: '3.40',
          unit_price: '0.85',
          approx_size: false,
          size_format: 'l',
          total_units: null,
          unit_selector: true,
          bunch_selector: false,
          drained_weight: null,
          selling_method: 0,
          tax_percentage: '10.000',
          price_decreased: false,
          reference_price: '3.400',
          min_bunch_amount: 1.0,
          reference_format: 'L',
          previous_unit_price: null,
          increment_bunch_amount: 1.0,
        },
        unavailable_weekdays: [],
      },
    },
    {
      quantity: 1.0,
      sources: ['+PL'],
      version: 2,
      product: {
        id: '52750',
        slug: 'bebida-kefir-fresa-platano-hacendado-botella',
        limit: 999,
        badges: {
          is_water: false,
          requires_age_check: false,
        },
        status: null,
        packaging: 'Bottle',
        published: true,
        share_url:
          'https://sta.tech.mercadona.es/product/52750/bebida-kefir-fresa-platano-hacendado-botella',
        thumbnail:
          'https://sta-mercadona.imgix.net/images/dd289147f3d6ee7437c4a9b701adf6ec.jpg?fit=crop&h=300&w=300',
        categories: [
          {
            id: 11,
            name: 'Dessert & yoghurt',
            level: 0,
            order: 597,
          },
        ],
        display_name: 'Strawberry and banana Kefir drink Hacendado',
        unavailable_from: null,
        price_instructions: {
          iva: 4,
          is_new: false,
          is_pack: false,
          pack_size: null,
          unit_name: null,
          unit_size: 0.25,
          bulk_price: '3.40',
          unit_price: '0.85',
          approx_size: false,
          size_format: 'kg',
          total_units: null,
          unit_selector: true,
          bunch_selector: false,
          drained_weight: null,
          selling_method: 0,
          tax_percentage: '4.000',
          price_decreased: false,
          reference_price: '3.400',
          min_bunch_amount: 1.0,
          reference_format: 'kg',
          previous_unit_price: null,
          increment_bunch_amount: 1.0,
        },
        unavailable_weekdays: [],
      },
    },
  ],
  open_order_id: null,
  summary: {
    total: '7.21',
  },
  products_count: 3,
}

const cocoKefirProduct = {
  product: {
    id: '15664',
    slug: 'bebida-kefir-coco-hacendado-botella',
    limit: 999,
    badges: {
      is_water: false,
      requires_age_check: false,
    },
    status: null,
    packaging: 'Bottle',
    published: true,
    share_url:
      'https://sta.tech.mercadona.es/product/15664/bebida-kefir-coco-hacendado-botella',
    thumbnail:
      'https://sta-mercadona.imgix.net/images/479a0815ddf6e4b2e5c7c82c3832e99c.jpg?fit=crop&h=300&w=300',
    categories: [
      {
        id: 11,
        name: 'Dessert & yoghurt',
        level: 0,
        order: 597,
        categories: [
          {
            id: 108,
            name: 'Liquid yoghurt',
            level: 1,
            order: 597,
            categories: [
              {
                id: 866,
                name: 'Cholesterol & others',
                level: 2,
                order: 597,
              },
            ],
          },
        ],
      },
    ],
    display_name: 'Coconut Kefir drink Hacendado',
    unavailable_from: null,
    price_instructions: {
      iva: 10,
      is_new: false,
      is_pack: false,
      pack_size: null,
      unit_name: null,
      unit_size: 0.25,
      bulk_price: '4.40',
      unit_price: '1.10',
      approx_size: false,
      size_format: 'kg',
      total_units: null,
      unit_selector: true,
      bunch_selector: false,
      drained_weight: null,
      selling_method: 0,
      price_decreased: false,
      reference_price: '4.400',
      min_bunch_amount: 1.0,
      reference_format: 'kg',
      previous_unit_price: null,
      increment_bunch_amount: 1.0,
    },
    unavailable_weekdays: [],
  },
  recommended_quantity: 1.0,
  source: 'shopping-list',
  source_code: 'SL',
}

export {
  cartWithMilka,
  shoppingLists,
  shoppingListDetail,
  productShoppingLists,
  emptyShoppingListDetail,
  cartWithShoppingListDetail,
  shoppingListDetailMilkaElement,
  cocoKefirProduct,
}
