export default {
  id: 1234,
  address: {
    id: 1,
    address: "Carrer d'Alboraia, 10, 46010 València, Valencia, España",
    address_detail: '1',
    postal_code: '46010',
    latitude: '39.48061550',
    longitude: '-0.37110230',
    comments: 'assss',
    permanent_address: true,
  },
  payment_method: {
    id: 104,
    credit_card_type: 'visa',
    credit_card_number: '1111',
    expires_month: '01',
    expires_year: '2020',
    default_card: false,
  },
  slot: {
    id: '26',
    start: '2017-09-20T09:00:00Z',
    end: '2017-09-20T10:00:00Z',
    price: '0.00',
    available: true,
  },
  cart: [
    {
      quantity: 6,
      selling_method: 0,
      product: {
        id: 77493,
        name: 'Aceite solar (sin factor de proteccion - spray)',
        thumbnail:
          'https://storage.googleapis.com/itg_statics_mimercadona/media/product_images/93/77493/77493.jpg',
        badges: {
          frozen: false,
          watermilk: false,
          sugar_free: false,
          gluten_free: false,
          lactose_free: false,
          refrigerated: false,
          requires_age_check: false,
          prohibited_to_minors: false,
        },
        price_instructions: {
          unit_size: 0.2,
          bulk_price: '39.50',
          size_aprox: false,
          unit_price: '7.90',
          bulk_measure: 'l',
          weight_drained: false,
          mini_size: null,
          pack_size: null,
          is_pack: false,
          increment_bulk_amount: 0.25,
          min_bulk_amount: 0.5,
        },
      },
    },
    {
      quantity: 4,
      selling_method: 0,
      product: {
        id: 66676,
        name: "Vino rosado gas lambrusco dell' emilia 750 ml",
        display_name: "Vino rosado gas lambrusco dell' emilia 750 ml",
        unit_name: null,
        thumbnail:
          'https://storage.googleapis.com/itg_statics_mimercadona/media/product_images/76/66676/66676.jpg',
        badges: {
          frozen: false,
          watermilk: false,
          sugar_free: false,
          gluten_free: false,
          lactose_free: false,
          refrigerated: false,
          prohibited_to_minors: false,
          requires_age_check: true,
          is_water: false,
        },
        price_instructions: {
          unit_size: 0.75,
          bulk_price: '2.25',
          size_aprox: false,
          unit_price: '1.69',
          approx_size: null,
          size_format: 'l',
          bulk_measure: 'l',
          drained_weight: null,
          weight_drained: null,
          mini_size: null,
          pack_size: null,
          is_pack: false,
          total_units: null,
          increment_bulk_amount: 0.25,
          min_bulk_amount: 0.5,
          increment_bunch_amount: 0.25,
          min_bunch_amount: 0.5,
          unit_name: null,
          price_decreased: false,
        },
      },
    },
  ],
  requires_age_check: true,
  summary: {
    price: '47.40',
  },
  order_id: 12,
}
