import { PAYMENT_STATUS } from '../../payment/constants'
import { STATUSES } from '../constants'

export const orderStatuses = [
  {
    name: 'cancelled by user',
    order: { status: STATUSES.CANCELLED_BY_USER },
    isPrintable: false,
    hasEstimatedPrice: true,
    isEditable: false,
    isCancelable: false,
    isRepeatable: true,
    isFinal: true,
    isDisrupted: false,
    isCancelled: true,
    beRated: false,
  },
  {
    name: 'cancelled by system',
    order: { status: STATUSES.CANCELLED_BY_SYSTEM },
    isPrintable: false,
    hasEstimatedPrice: true,
    isEditable: false,
    isCancelable: false,
    isRepeatable: true,
    isFinal: true,
    isDisrupted: false,
    isCancelled: true,
    beRated: false,
  },
  {
    name: 'delivered',
    order: { status: STATUSES.DELIVERED },
    isPrintable: true,
    hasEstimatedPrice: false,
    isEditable: false,
    isCancelable: false,
    isRepeatable: true,
    isFinal: true,
    isDisrupted: false,
    isCancelled: false,
    beRated: true,
  },
  {
    name: 'delivering',
    order: { status: STATUSES.DELIVERING },
    isPrintable: true,
    hasEstimatedPrice: false,
    isEditable: false,
    isCancelable: false,
    isRepeatable: false,
    isFinal: false,
    isDisrupted: false,
    isCancelled: false,
    beRated: false,
  },
  {
    name: 'disrupted by customer',
    order: { status: STATUSES.DISRUPTED_BY_CUSTOMER },
    isPrintable: true,
    hasEstimatedPrice: false,
    isEditable: false,
    isCancelable: false,
    isRepeatable: false,
    isFinal: false,
    isDisrupted: true,
    isCancelled: false,
    beRated: false,
  },
  {
    name: 'disrupted by system',
    order: { status: STATUSES.DISRUPTED_BY_SYSTEM },
    isPrintable: true,
    hasEstimatedPrice: false,
    isEditable: false,
    isCancelable: false,
    isRepeatable: false,
    isFinal: false,
    isDisrupted: true,
    isCancelled: false,
    beRated: false,
  },
  {
    name: 'ongoing',
    order: { status: STATUSES.CONFIRMED },
    isPrintable: false,
    hasEstimatedPrice: true,
    isEditable: true,
    isCancelable: true,
    isRepeatable: false,
    isFinal: false,
    isDisrupted: false,
    isCancelled: false,
    beRated: false,
  },
  {
    name: 'prepared',
    order: { status: STATUSES.PREPARED },
    isPrintable: true,
    hasEstimatedPrice: false,
    isEditable: false,
    isCancelable: false,
    isRepeatable: false,
    isFinal: false,
    isDisrupted: false,
    isCancelled: false,
    beRated: false,
  },
  {
    name: 'preparing',
    order: { status: STATUSES.PREPARING },
    isPrintable: false,
    hasEstimatedPrice: true,
    isEditable: false,
    isCancelable: false,
    isRepeatable: false,
    isFinal: false,
    isDisrupted: false,
    isCancelled: false,
    beRated: false,
  },
  {
    name: 'payment disrupted',
    order: {
      status: STATUSES.CONFIRMED,
      payment_status: PAYMENT_STATUS.FAILED,
    },
    isPrintable: false,
    hasEstimatedPrice: false,
    isEditable: false,
    isCancelable: false,
    isRepeatable: false,
    isFinal: false,
    isDisrupted: true,
    isCancelled: false,
    beRated: false,
  },
]
