export enum AddPaymentMethodModalCustomMode {
  CHOOSE = 'CHOOSE_PAYMENT_METHOD_MODE',
  CURRENT_PAYMENT_METHODS_RESOLVE_PAYMENT_INCIDENT = 'CURRENT_PAYMENT_METHODS_RESOLVE_PAYMENT_INCIDENT_MODE',
  CURRENT_PAYMENT_METHODS = 'CURRENT_PAYMENT_METHODS_MODE',
  RESOLVE_PAYMENT_INCIDENT = 'RESOLVE_PAYMENT_INCIDENT_MODE',
  RESOLVE_PAYMENT_PENDING = 'RESOLVE_PAYMENT_PENDING_MODE',
}
