const { VITE_ACCEPTED_COOKIES, VITE_USER_INFO, VITE_DELIVERY_COOKIE } =
  import.meta.env

const COOKIES = {
  MO_DA: VITE_DELIVERY_COOKIE,
  MO_CA: VITE_ACCEPTED_COOKIES,
  MO_UI: VITE_USER_INFO,
  ZLCMID: '__zlcmid',
  AMPLITUDE: 'amplitude_id',
}

const NECESSARY_COOKIES_TRANSLATION_KEYS = {
  MO_DA: '__mo_da',
  MO_CA: '__mo_ca',
  MO_UI: '__mo_ui',
  ZLCMID: '__zlcmid',
  AMPLITUDE: 'amplitude_id',
}

const REQUIRED_ANALYTICS_COOKIES_TRANSLATION_KEYS = {
  AMPLITUDE_REQUIRED_ANALYTICS: 'amplitude_id_required_analytics',
}

const THIRDPARTY_COOKIES_TRANSLATION_KEYS = {
  GAEXP: '_gaexp',
  GA: '_ga',
  GID: '_gid',
}

const NECESSARY_COOKIES = [
  COOKIES.MO_DA,
  COOKIES.MO_CA,
  COOKIES.MO_UI,
  COOKIES.ZLCMID,
]

export {
  NECESSARY_COOKIES,
  COOKIES,
  NECESSARY_COOKIES_TRANSLATION_KEYS,
  REQUIRED_ANALYTICS_COOKIES_TRANSLATION_KEYS,
  THIRDPARTY_COOKIES_TRANSLATION_KEYS,
}
