export const orderProductsMock = {
  66313: {
    id: 66313,
    display_name: 'Vino rosado D.O. Rioja',
    unit_name: null,
    thumbnail:
      'https://sta-mercadona.imgix.net/20180212/13/66313/66313_00_00.jpg?fit=crop&h=300&w=300',
    badges: {
      requires_age_check: true,
      is_water: false,
    },
    price_instructions: {
      is_new: false,
      pack_size: null,
      unit_name: null,
      unit_size: 0.75,
      bulk_price: '2.52',
      unit_price: '1.89',
      approx_size: false,
      size_format: 'l',
      total_units: null,
      drained_weight: null,
      price_decreased: false,
      min_bunch_amount: 0.5,
      increment_bunch_amount: 0.25,
      reference_price: '2.52',
      reference_format: 'L',
      mini_size: null,
      is_pack: false,
      increment_bulk_amount: 0.25,
      min_bulk_amount: 0.5,
    },
    quantity: 1,
    selling_method: 0,
    product: {
      id: 66313,
      display_name: 'Vino rosado D.O. Rioja',
      unit_name: null,
      thumbnail:
        'https://sta-mercadona.imgix.net/20180212/13/66313/66313_00_00.jpg?fit=crop&h=300&w=300',
      badges: {
        requires_age_check: true,
        is_water: false,
      },
      price_instructions: {
        is_new: false,
        pack_size: null,
        unit_name: null,
        unit_size: 0.75,
        bulk_price: '2.52',
        unit_price: '1.89',
        approx_size: false,
        size_format: 'l',
        total_units: null,
        drained_weight: null,
        price_decreased: false,
        min_bunch_amount: 0.5,
        increment_bunch_amount: 0.25,
        reference_price: '2.52',
        reference_format: 'L',
        mini_size: null,
        is_pack: false,
        increment_bulk_amount: 0.25,
        min_bulk_amount: 0.5,
      },
    },
    total: 1.89,
    order: 1,
  },
  66314: {
    id: 66314,
    display_name: 'Vino rosado D.O. Rioja',
    unit_name: null,
    thumbnail:
      'https://sta-mercadona.imgix.net/20180212/13/66313/66313_00_00.jpg?fit=crop&h=300&w=300',
    badges: {
      requires_age_check: true,
      is_water: false,
    },
    price_instructions: {
      is_new: false,
      pack_size: null,
      unit_name: null,
      unit_size: 0.75,
      bulk_price: '2.52',
      unit_price: '1.89',
      approx_size: false,
      size_format: 'l',
      total_units: null,
      drained_weight: null,
      price_decreased: false,
      min_bunch_amount: 0.5,
      increment_bunch_amount: 0.25,
      reference_price: '2.52',
      reference_format: 'L',
      mini_size: null,
      is_pack: false,
      increment_bulk_amount: 0.25,
      min_bulk_amount: 0.5,
    },
    quantity: 1,
    selling_method: 0,
    product: {
      id: 66314,
      display_name: 'Vino rosado D.O. Rioja',
      unit_name: null,
      thumbnail:
        'https://sta-mercadona.imgix.net/20180212/13/66313/66313_00_00.jpg?fit=crop&h=300&w=300',
      badges: {
        requires_age_check: true,
        is_water: false,
      },
      price_instructions: {
        is_new: false,
        pack_size: null,
        unit_name: null,
        unit_size: 0.75,
        bulk_price: '2.52',
        unit_price: '1.89',
        approx_size: false,
        size_format: 'l',
        total_units: null,
        drained_weight: null,
        price_decreased: false,
        min_bunch_amount: 0.5,
        increment_bunch_amount: 0.25,
        reference_price: '2.52',
        reference_format: 'L',
        mini_size: null,
        is_pack: false,
        increment_bulk_amount: 0.25,
        min_bulk_amount: 0.5,
      },
    },
    total: 1.89,
    order: 1,
  },
}
